# Generated by Django 2.2 on 2021-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='Model')),
                ('vendor', models.CharField(blank=True, max_length=64, null=True, verbose_name='Vendor')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('condition', models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('To Repair', 'To Repair')], max_length=32, null=True)),
            ],
        ),
    ]
