# Generated by Django 2.2 on 2021-06-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=128, null=True, verbose_name='Author')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Title')),
                ('genre', models.CharField(blank=True, choices=[('Non Fiction', 'Non Fiction'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('History', 'History')], max_length=64, null=True, verbose_name='Genre')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
