# Generated by Django 2.2 on 2021-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
