# Generated by Django 2.2 on 2021-06-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='highlighted',
        ),
    ]
