# Generated by Django 2.2 on 2021-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trans_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Transaction Id'),
        ),
    ]
