# Generated by Django 2.2 on 2021-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_order_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trans_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Transaction Id'),
        ),
    ]
