# Generated by Django 2.2 on 2021-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210618_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(null=True, verbose_name='Total price'),
        ),
    ]
