# Generated by Django 2.2 on 2021-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20210618_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_delivered',
            field=models.IntegerField(null=True, verbose_name='Delivered'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_ordered',
            field=models.IntegerField(null=True, verbose_name='Ordered'),
        ),
    ]
